[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Text.ASCIIEncoding))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Text.UnicodeEncoding))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Text.UTF32Encoding))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Text.UTF7Encoding))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Text.UTF8Encoding))]
