[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.OrderedParallelQuery<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.ParallelEnumerable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.ParallelExecutionMode))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.ParallelMergeOptions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.ParallelQuery))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.ParallelQuery<>))]
