[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Drawing.Color))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Drawing.Point))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Drawing.PointF))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Drawing.Rectangle))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Drawing.RectangleF))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Drawing.Size))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Drawing.SizeF))]
