[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.NetworkInformation.IPStatus))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.NetworkInformation.Ping))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.NetworkInformation.PingException))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.NetworkInformation.PingOptions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.NetworkInformation.PingReply))]
