[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Console))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ConsoleCancelEventArgs))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ConsoleCancelEventHandler))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ConsoleColor))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ConsoleKey))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ConsoleKeyInfo))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ConsoleModifiers))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.ConsoleSpecialKey))]
