[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(Microsoft.Win32.SafeHandles.SafeWaitHandle))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.HandleInheritability))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.InteropServices.CriticalHandle))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.InteropServices.SafeHandle))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Threading.WaitHandleExtensions))]
