[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.Enumerable))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.IGrouping<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.ILookup<,>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.IOrderedEnumerable<>))]
[assembly:System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Linq.Lookup<,>))]
